language: python
sudo: required
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/build/amn41/rasa_stack/data
python:
- '3.5'
- '3.6'
install:
- pip install -r dev-requirements.txt
- pip install -e .
- pip install coveralls==1.3.0
- pip list
jobs:
  include:
  - stage: deploy
    python: 3.6
    install: skip
    script: skip
    deploy:
      provider: pypi
      user: tmbo
      distributions: sdist bdist_wheel
      true:
        branch: master
        tags: true
      password:
        secure: a088vPR2oCQ1L61R33k76fynsWW8a/Kg5kNAYzdbxTe5kTLa/PCf7UrF8DRoBQc0dkZogM2SiT9m23JFeTIOdab2H/dj0wGWSMskJx92S62KDidWlb4BJ/+zZfycO0PuS/WhO9qOCjzM94cPKXXP/6tlpU9eRHHsjag+wihhK64cTg3NkGNGzETwvcO9sonUZxQ98KfLztbNF5p7WARc39CqQTH5v8ga8Zv2kdVIpvwIPk1oAlpvuippuAj3XnyRPfxSuDyMQlrM+VRf34JkL194bT14ugYQ/tLlJh5XU3mtmJjyFp1d9Xs6vjVCEUru2CXbz9QZUPWeDhjlescaD1JrYCCMMxjURjQdqGGcaYtACB7DDnQzIbx07uVORBLnoVb4O0z/P5ZE12Jp1RF67nQn9ZbdLGvuLj+ZhDrQd23vn5eK+mmiYNKKlUHyavS0JfeJbNU8tIw8boRZNZhuc4F4zR1OkPaq7/wgt4cShjDWYFGsuXWWKT5y1U+MZe9XU3ltClasNhLtRLWuNEKg4dlevykXAV7xryNgZhDsIPztzYOfT1OYMBVu5pJg2GoMli1LYYXMZB5w32NTdVtHuPPt59PbNe7HooNZzKX/jE+TE3ujDfaF5F3mrCo2wWqZ76XUUx2vdDT7xVGLdZgjC/lHhFVWyMB1L5ZDaYI8MbA=
before_script:
- bash test_mypy.sh
before_install:
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
script:
- echo "SCRIPT SECTION"
